### ISSUE TITLE
How to show "*.bundle" file's  info ?

### ISSUE THREAD

**Issue by louisome** [nesrak1/UABEA#199]
It can open .bundle file, but cannot show the info~

**Comment by nesrak1** [comment]
Have you tried at3 nightly?
https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/at3/uabea-windows.zip

**Comment by louisome** [comment]
Ohh~
U help me a lot, I want to buy u a coffee.

**Comment by louisome** [comment]
But when i change something, then save. 
It will not be load by game.
log like this:
"E/Unity: async texture load: failed to load FingerIcon from archive:/CAB-0831a91bb38d60ce779a931cfdcecb00/CAB-0831a91bb38d60ce779a931cfdcecb00.resS"

**Comment by louisome** [comment]
ohhh, if i use other computer, it's everything ok.
why this happen?

**Comment by nesrak1** [comment]
I'm not sure how that happened, but I fixed a different issue involving compression. I don't know if it'll fix your issue or why it would only happen on one computer but not another.

**Comment by louisome** [comment]
Thank you for your reply, but the error still exist~
I try to find the different between two computer ( maybe some environment setting or dotnet version, but most of them are the same~).

**Comment by louisome** [comment]
The newest version decompress **.bundle** file suceess(save to disk not memory), but cannot show the info(click the info button)...
The previous one can show the info, but decompress **.bundle** file fail ~

Here is the demo file:

[screens_assets_all_494611d168cb2a20171970f010bebb30.zip](https://github.com/nesrak1/UABEA/files/9857028/screens_assets_all_494611d168cb2a20171970f010bebb30.zip)

**Comment by nesrak1** [comment]
I can't reproduce on the latest at3 nightly. I can decompress to both memory and file, make some changes and save, reload the file just fine, compress to both lz4 and lzma and reopen those fine as well. You're sure you're using the latest version? Maybe you are unpacking an old version on top of a new version? There's nothing in the code besides the texture plugin that would be platform specific.

**Comment by louisome** [comment]
ok..i try to delete all verion uabea and try again later..

And i find the different is i7 10700(it doesn't work) and i5 12490(it work).

**Comment by louisome** [comment]
ohh ~ it's ok for some .bundle, I delete all versions, and redownload the newest one.
But one of .bundle file, replace one texture and save, it will crash for the game.
But other .bundle file has not this problem, confusing...
(same image, different .bundle files which also has the same image)
